FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM golang:1.24-alpine
WORKDIR /app
COPY --from=builder /app/server .
COPY migrations/ migrations/
EXPOSE 8080
CMD ["./server"]
